name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install dependencies (musl)
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt update
          sudo apt install musl-tools

      - name: Cargo build
        run: |
          rustup toolchain install stable --profile minimal -t ${{ matrix.target }}
          cargo build --target ${{ matrix.target }}
        env:
          GEN_ARTIFACTS: artifacts

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Restore fetcher cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: nix-cache-${{ hashFiles('flake.lock', 'src/**', 'tests/**/*.toml') }}
          path: ~/.cache/nix
          restore-keys: nix-cache-

      - name: Install nix
        uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Cargo test
        run: cargo test

      - name: Save fetcher cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: always()
        with:
          key: nix-cache-${{ hashFiles('flake.lock', 'src/**', 'tests/**/*.toml') }}
          path: ~/.cache/nix

  clippy-rustfmt:
    name: clippy-rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Cargo: clippy, fmt"
        run: |
          rustup toolchain install stable --profile minimal -c clippy
          rustup toolchain install nightly --profile minimal -c rustfmt
          cargo +stable clippy -- -D warnings
          cargo +nightly fmt -- --check
